### PR TITLE
Singularize Class Name Bug

### LINKED ISSUE #46: Can't find custom parser with _data name
### Issue
Decanter is unable to find a custom parser named `CheckInFieldData`.

### Error Message
`cannot find parser CheckInFieldDatumParser`.

### Steps to Reproduce
Here's my current project structure and relevant code:
- Decanter file exists named `check_in_decanter.rb` in `app/decanters/`.
- Parser file exists named `check_in_field_data_parser.rb` in `lib/decanter/parsers/`.

`check_in_decanter.rb`:
```ruby
class CheckInDecanter < Decanter::Base
  strict true

  input :storm_detail_id, :string
  input :operator_id, :string
  input :check_in_time, :date_time, parse_format: '%a, %d %b %Y %H:%M:%S %z'
  input :check_out_time, :date_time, parse_format: '%a, %d %b %Y %H:%M:%S %z'
  input :field_data, :check_in_field_data
end
```

`check_in_field_data_parser.rb`:
```ruby
class CheckInFieldDataParser < Decanter::Parser::HashParser
  ALLOWED_FIELD_DATA = %w[check_in_coordinates check_out_coordinates].freeze

  parser do |_name, val, _options|
    hash = {}
    val.each do |k, v|
      hash[k] = v if ALLOWED_FIELD_DATA.include?(k.to_s)
    end
    { field_data: hash }
  end
end
```

Changing the parser name to anything else fixes the problem. For example, `FooParser`, or adding a letter e.g. `CheckInFieldDatazParser`. It seems like there's something specific about `_data`.

### PR DESCRIPTION
**Pull request by mrjonesbot**
Resolve #46 

When passing a symbol to `klass_or_sym_to_str`, decanter would convert to a string, singularize, then camelize before attemping to constantize. This would transform any names with `_data` into `_datum`, raising an `ArgumentError`: "cannot lookup parser for...".

When a class is passed, we don't attempt to singularize the name value.

To address fringe cases like `data => datum`, decanter will first try to find the singularized version of the class, then fallback to the non-singularized version. If neither are found, it will raise an `ArgumentError` as expected.

### CODE REVIEW

File: lib/decanter/parser.rb [hunk 1]
```diff
@@ -16,17 +15,44 @@ def klass_or_sym_to_str(klass_or_sym)
...
       end
 
       # convert from a string to a constant
       def parser_constantize(parser_str)
+        # safe_constantize returns nil if match not found
         parser_str.safe_constantize ||
-        "Decanter::Parser::".concat(parser_str).safe_constantize ||
-        raise(NameError.new("cannot find parser #{parser_str}"))
+          concat_str(parser_str).safe_constantize ||
+          raise(NameError.new("cannot find parser #{parser_str}"))
```
Comment (rkillackey) [inline lib/decanter/parser.rb]: I think Codeclimate is complaining about the syntax of the `raise` call here... Usually it's something like `raise NameError, "cannot find parser ..."`.

File: lib/decanter/parser.rb [hunk 2]
```diff
@@ -16,17 +15,44 @@ def klass_or_sym_to_str(klass_or_sym)
...
+      end
+
+      # extract string transformation strategies
+      def symbol_to_string(klass_or_sym)
```
Comment (rkillackey) [inline lib/decanter/parser.rb]: We might want to move these methods to something like a `Utils` module, but I think it's good for now!

File: lib/decanter/parser.rb (hunk 1 above)
Comment (mrjonesbot) [reply lib/decanter/parser.rb]: @rkillackey I'm not seeing those CodeClimate comments, my side is all green.
screen shot 2017-12-04 at 4 30 27 pm

File: lib/decanter/parser.rb (hunk 2 above)
Comment (mrjonesbot) [reply lib/decanter/parser.rb]: @rkillackey In my attempt, I received..help wanted!
screen shot 2017-12-04 at 4 31 40 pm
